apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: bharats487/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8989   
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8989
      targetPort: 8989
  selector:
    name: springboot

